// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_associate.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2SServiceAssociate struct {
	//类型名称
	TypeName string `protobuf:"bytes,1,opt,name=typeName,proto3" json:"typeName,omitempty"`
	//服务编号
	Pid                  int64    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SServiceAssociate) Reset()         { *m = C2SServiceAssociate{} }
func (m *C2SServiceAssociate) String() string { return proto.CompactTextString(m) }
func (*C2SServiceAssociate) ProtoMessage()    {}
func (*C2SServiceAssociate) Descriptor() ([]byte, []int) {
	return fileDescriptor_949a558e1060bc2c, []int{0}
}

func (m *C2SServiceAssociate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SServiceAssociate.Unmarshal(m, b)
}
func (m *C2SServiceAssociate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SServiceAssociate.Marshal(b, m, deterministic)
}
func (m *C2SServiceAssociate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SServiceAssociate.Merge(m, src)
}
func (m *C2SServiceAssociate) XXX_Size() int {
	return xxx_messageInfo_C2SServiceAssociate.Size(m)
}
func (m *C2SServiceAssociate) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SServiceAssociate.DiscardUnknown(m)
}

var xxx_messageInfo_C2SServiceAssociate proto.InternalMessageInfo

func (m *C2SServiceAssociate) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *C2SServiceAssociate) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type S2CServiceAssociate struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CServiceAssociate) Reset()         { *m = S2CServiceAssociate{} }
func (m *S2CServiceAssociate) String() string { return proto.CompactTextString(m) }
func (*S2CServiceAssociate) ProtoMessage()    {}
func (*S2CServiceAssociate) Descriptor() ([]byte, []int) {
	return fileDescriptor_949a558e1060bc2c, []int{1}
}

func (m *S2CServiceAssociate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CServiceAssociate.Unmarshal(m, b)
}
func (m *S2CServiceAssociate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CServiceAssociate.Marshal(b, m, deterministic)
}
func (m *S2CServiceAssociate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CServiceAssociate.Merge(m, src)
}
func (m *S2CServiceAssociate) XXX_Size() int {
	return xxx_messageInfo_S2CServiceAssociate.Size(m)
}
func (m *S2CServiceAssociate) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CServiceAssociate.DiscardUnknown(m)
}

var xxx_messageInfo_S2CServiceAssociate proto.InternalMessageInfo

//ping
type C2SServicePing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SServicePing) Reset()         { *m = C2SServicePing{} }
func (m *C2SServicePing) String() string { return proto.CompactTextString(m) }
func (*C2SServicePing) ProtoMessage()    {}
func (*C2SServicePing) Descriptor() ([]byte, []int) {
	return fileDescriptor_949a558e1060bc2c, []int{2}
}

func (m *C2SServicePing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SServicePing.Unmarshal(m, b)
}
func (m *C2SServicePing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SServicePing.Marshal(b, m, deterministic)
}
func (m *C2SServicePing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SServicePing.Merge(m, src)
}
func (m *C2SServicePing) XXX_Size() int {
	return xxx_messageInfo_C2SServicePing.Size(m)
}
func (m *C2SServicePing) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SServicePing.DiscardUnknown(m)
}

var xxx_messageInfo_C2SServicePing proto.InternalMessageInfo

type S2CServicePing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CServicePing) Reset()         { *m = S2CServicePing{} }
func (m *S2CServicePing) String() string { return proto.CompactTextString(m) }
func (*S2CServicePing) ProtoMessage()    {}
func (*S2CServicePing) Descriptor() ([]byte, []int) {
	return fileDescriptor_949a558e1060bc2c, []int{3}
}

func (m *S2CServicePing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CServicePing.Unmarshal(m, b)
}
func (m *S2CServicePing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CServicePing.Marshal(b, m, deterministic)
}
func (m *S2CServicePing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CServicePing.Merge(m, src)
}
func (m *S2CServicePing) XXX_Size() int {
	return xxx_messageInfo_S2CServicePing.Size(m)
}
func (m *S2CServicePing) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CServicePing.DiscardUnknown(m)
}

var xxx_messageInfo_S2CServicePing proto.InternalMessageInfo

func init() {
	proto.RegisterType((*C2SServiceAssociate)(nil), "proto.c2s_service_associate")
	proto.RegisterType((*S2CServiceAssociate)(nil), "proto.s2c_service_associate")
	proto.RegisterType((*C2SServicePing)(nil), "proto.c2s_service_ping")
	proto.RegisterType((*S2CServicePing)(nil), "proto.s2c_service_ping")
}

func init() { proto.RegisterFile("service_associate.proto", fileDescriptor_949a558e1060bc2c) }

var fileDescriptor_949a558e1060bc2c = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x8d, 0x4f, 0x2c, 0x2e, 0xce, 0x4f, 0xce, 0x4c, 0x2c, 0x49, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xae, 0x5c, 0xa2, 0xc9, 0x46, 0xc5, 0xf1, 0x18,
	0xaa, 0x84, 0xa4, 0xb8, 0x38, 0x4a, 0x2a, 0x0b, 0x52, 0xfd, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x01, 0x2e, 0xe6, 0x82, 0xcc, 0x14, 0x09, 0x26, 0x05,
	0x46, 0x0d, 0xe6, 0x20, 0x10, 0x53, 0x49, 0x9c, 0x4b, 0xb4, 0xd8, 0x28, 0x19, 0xd3, 0x18, 0x25,
	0x21, 0x2e, 0x01, 0x64, 0xf3, 0x0b, 0x32, 0xf3, 0xd2, 0x41, 0x62, 0xc8, 0x8a, 0x41, 0x62, 0x49,
	0x6c, 0x60, 0xe7, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x7c, 0xf2, 0x37, 0xb0, 0x00,
	0x00, 0x00,
}
